### ISSUE TITLE
combine supabase middleware with next-intl middleware

### ISSUE THREAD

**Issue by mengxi-ream** [ElectricCodeGuy/SupabaseAuthWithSSR#1]
Hello, thank you for the great template applying `@supabase/ssr`

After `@supabase/ssr` was launched, its middleware becomes different from the previous version.

My current code of `middleware.ts` in the root to combine supabase middleware with next-intl middleware is :
```ts
import createIntlMiddleware from "next-intl/middleware";
import { NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/middleware";

export default async function middleware(req: NextRequest) {
  const handleI18nRouting = createIntlMiddleware({
    locales: ["en", "zh", "zh-TW"],
    defaultLocale: "en",
  });
  const res = handleI18nRouting(req);
  const { supabase, response } = createClient(req);
  await supabase.auth.getSession();
  return res;
}
export const config = {
  matcher: ["/((?!_next|.*\\..*|auth).*)"],
};
```

This definitely has problem because just return `res` from `handleI18nRouting`, we actually need to found a good way to combine response from `handleI18nRouting` and `createClient`

This is the [code](https://github.com/amannn/next-intl/blob/208b4ea85f507672ba6933a5fabc78e5e088558b/packages/next-intl/src/middleware.tsx#L9) for createIntlMiddleware

```ts
export default function createIntlMiddleware({
  defaultLocale,
  locales
}: NextIntlMiddlewareConfig) {
  const i18n = {
    locales,
    defaultLocale
  };

  return function middleware(request: NextRequest) {
    // Ideally we could use the `headers()` and `cookies()` API here
    // as well, but they are currently not available in middleware.
    const locale = resolveLocale(
      i18n,
      request.headers,
      request.cookies,
      request.nextUrl.pathname
    );

    const isRoot = request.nextUrl.pathname === ROOT_URL;
    const isChangingLocale =
      request.cookies.get(COOKIE_LOCALE_NAME)?.value !== locale;

    let response;
    if (isRoot) {
      response = NextResponse.redirect(new URL(ROOT_URL + locale, request.url));
    } else {
      let responseInit;

      // Only apply a header if absolutely necessary
      // as this causes full page reloads
      if (isChangingLocale) {
        request.headers.set(HEADER_LOCALE_NAME, locale);

        responseInit = {
          request: {
            headers: request.headers
          }
        };
      }

      response = NextResponse.next(responseInit);
    }

    if (isChangingLocale) {
      response.cookies.set(COOKIE_LOCALE_NAME, locale);
    }

    return response;
  };
}
```

This is the code for `createClient`

```ts
import { type NextRequest, NextResponse } from "next/server";
import { type CookieOptions, createServerClient } from "@supabase/ssr";

export const createClient = (request: NextRequest) => {
  // Create an unmodified response
  let response = NextResponse.next({
    request: {
      headers: request.headers,
    },
  });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return request.cookies.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          // If the cookie is updated, update the cookies for the request and response
          request.cookies.set({
            name,
            value,
            ...options,
          });
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          });
          response.cookies.set({
            name,
            value,
            ...options,
          });
        },
        remove(name: string, options: CookieOptions) {
          // If the cookie is removed, update the cookies for the request and response
          request.cookies.set({
            name,
            value: "",
            ...options,
          });
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          });
          response.cookies.set({
            name,
            value: "",
            ...options,
          });
        },
      },
    },
  );

  return { supabase, response };
};
```

Here is the [doc](https://next-intl-docs.vercel.app/docs/routing/middleware#composing-other-middlewares) for how to combine other middleware with middleware of `next-intl`

What's the best practice to do combination?

**Comment by ElectricCodeGuy** [comment]
Hello

Hmm im not 100% sure, but i would try something like this:

`
import createIntlMiddleware from "next-intl/middleware";
import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/middleware";

export default async function middleware(req: NextRequest) {
  // Step 1: Handle i18n routing
  const handleI18nRouting = createIntlMiddleware({
    locales: ["en", "zh", "zh-TW"],
    defaultLocale: "en",
  });

  let res = handleI18nRouting(req);

  // Step 2: Create Supabase client and get the session
  const { supabase, response: supabaseResponse } = createClient(req);
  await supabase.auth.getSession();

  // Step 3: Combine responses if necessary
  // If Supabase middleware modified the response, we need to merge the changes
  if (supabaseResponse.headers.get('set-cookie')) {
    // Here you would merge the cookies from the Supabase response into the i18n response
    const cookies = supabaseResponse.headers.get('set-cookie');
    res.headers.append('set-cookie', cookies);
  }

  // If the locale is changing and a redirect is necessary, that will be handled by the i18n middleware
  // If not, we return the combined response
  return res;
}

export const config = {
  matcher: ["/((?!_next|.*\\..*|auth).*)"],
};
`
This is Psudo code, so the syntax is not 100% correct.

So in essence we first determine the locales, Then create the Supabase client and retrieve the session/user. Then if the middleware modifies the to cookie we make sure that this is also applied to the response created by the next-intl

I must emphasize that I am not sure, and i think the best option would be to test out the different options and see what works best. I have not implemented this yet into my own project.
