### ISSUE TITLE
[Question] No session reset password

### ISSUE THREAD

**Issue by Max0u** [ElectricCodeGuy/SupabaseAuthWithSSR#3]
Hello!
I'm trying to implement SSR with supabase on my personal project. I cloned and tried yours but every time I try to reset my password but I have the supabase error message `Auth session missing!`. I suspect that the endpoint /auth/confirm does not set cookies properly. I didn't change anything except the env var. Do you have any idea what could go wrong? (I'm using supabase locally)
Thank you!

**Comment by ElectricCodeGuy** [comment]
Hmmm, this might be true, its been some months since I last tested this. I will respond back when i have :)

**Comment by Max0u** [comment]
Alright thanks! I will deep dive on my side too

**Comment by ElectricCodeGuy** [comment]
Should be fixed now. I made an error when users signed in.
