### ISSUE TITLE
Open source scraper?

### ISSUE THREAD

**Issue by mhenrichsen** [ElectricCodeGuy/SupabaseAuthWithSSR#7]
Hi!

Awesome project. Do you plan on releasing the scraper?

**Comment by ElectricCodeGuy** [comment]
The one that uses tavily ?

**Comment by mhenrichsen** [comment]
Mainly for retsinformation.

**Comment by ElectricCodeGuy** [comment]
Der er ikke noget specielt med dem. Jeg laver et fetch til deres API og henter JSON og bruger pakken HTML-to-text og så insert ind i min database
